// ~~ Generated by projen. To modify, edit .projenrc.ts and run "npx projen".
import * as path from 'path';
import * as lambda from 'aws-cdk-lib/aws-lambda';
import { Construct } from 'constructs';

/**
 * Props for IdleMonitorFunction
 */
export interface IdleMonitorFunctionProps extends lambda.FunctionOptions {
}

/**
 * An AWS Lambda function which executes src/idle-monitor/idle-monitor.
 */
export class IdleMonitorFunction extends lambda.Function {
  constructor(scope: Construct, id: string, props?: IdleMonitorFunctionProps) {
    super(scope, id, {
      description: 'src/idle-monitor/idle-monitor.lambda.ts',
      ...props,
      runtime: new lambda.Runtime('nodejs20.x', lambda.RuntimeFamily.NODEJS),
      handler: 'index.handler',
      code: lambda.Code.fromAsset(path.join(__dirname, '../../assets/idle-monitor/idle-monitor.lambda')),
    });
  }
}