// ~~ Generated by projen. To modify, edit .projenrc.ts and run "npx projen".
import * as path from 'path';
import * as lambda from 'aws-cdk-lib/aws-lambda';
import { Construct } from 'constructs';

/**
 * Props for StatusCheckFunction
 */
export interface StatusCheckFunctionProps extends lambda.FunctionOptions {
}

/**
 * An AWS Lambda function which executes src/status-check/status-check.
 */
export class StatusCheckFunction extends lambda.Function {
  constructor(scope: Construct, id: string, props?: StatusCheckFunctionProps) {
    super(scope, id, {
      description: 'src/status-check/status-check.lambda.ts',
      ...props,
      runtime: new lambda.Runtime('nodejs22.x', lambda.RuntimeFamily.NODEJS),
      handler: 'index.handler',
      code: lambda.Code.fromAsset(path.join(__dirname, '../../assets/status-check/status-check.lambda')),
    });
  }
}