// ~~ Generated by projen. To modify, edit .projenrc.ts and run "npx projen".
import * as path from 'path';
import * as lambda from 'aws-cdk-lib/aws-lambda';
import { Construct } from 'constructs';

/**
 * Props for InstallerFunction
 */
export interface InstallerFunctionProps extends lambda.FunctionOptions {
}

/**
 * An AWS Lambda function which executes src/installer/installer.
 */
export class InstallerFunction extends lambda.Function {
  constructor(scope: Construct, id: string, props?: InstallerFunctionProps) {
    super(scope, id, {
      description: 'src/installer/installer.lambda.ts',
      ...props,
      runtime: new lambda.Runtime('nodejs20.x', lambda.RuntimeFamily.NODEJS),
      handler: 'index.handler',
      code: lambda.Code.fromAsset(path.join(__dirname, '../../assets/installer/installer.lambda')),
    });
  }
}