// ~~ Generated by projen. To modify, edit .projenrc.ts and run "npx projen".
import * as path from 'path';
import * as lambda from 'aws-cdk-lib/aws-lambda';
import { Construct } from 'constructs';

/**
 * Props for ResumeHandlerFunction
 */
export interface ResumeHandlerFunctionProps extends lambda.FunctionOptions {
}

/**
 * An AWS Lambda function which executes src/resume-handler/resume-handler.
 */
export class ResumeHandlerFunction extends lambda.Function {
  constructor(scope: Construct, id: string, props?: ResumeHandlerFunctionProps) {
    super(scope, id, {
      description: 'src/resume-handler/resume-handler.lambda.ts',
      ...props,
      runtime: new lambda.Runtime('nodejs20.x', lambda.RuntimeFamily.NODEJS),
      handler: 'index.handler',
      code: lambda.Code.fromAsset(path.join(__dirname, '../../assets/resume-handler/resume-handler.lambda')),
    });
  }
}